### ISSUE TITLE
Allure report generates the exception with full of Ansi codes

### ISSUE THREAD

**Issue by BhargavGurav** [allure-framework/allure2#2830]
### Describe the Bug

![allure-bug](https://github.com/user-attachments/assets/436d14f4-1f3c-48b1-ad54-0eedec14769f)
Allure generates the text like this, in like almost each case for me. Even I updated the allure but still it generates the same text in case of exception. The text contains ansi codes. I have attaced the decoded text in attachment but in the report it generates this text, I tried to solve it from libraries and codes but was unable.

### Steps to Reproduce

1. Just give some expected and actually comparison steps.

### Expected Behaviour

It should give text free from ansi which can be done in TS like stripAnsi(text).

### What Language are you using?

TypeScript

### What Framework/Allure Integration you are using?

allure-commandline

### What version of Allure Integration you are using?

2.30

### What version of Allure Report you are using?

2.30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
The issue is fixed in the latest allure-js releases

**Comment by BhargavGurav** [comment]
Thanks, I was searching for the whole module, but after 1-2 days I moved
forward to next tasks so almost forgot about it. Thank you 🙏

**Comment by BhargavGurav** [comment]
I am still facing the issue 

![Image](https://github.com/user-attachments/assets/64f2838b-31cf-4f5d-a289-6b494a4552d0)
i have this dependencies installed and still facing the issue

**Comment by baev** [comment]
Support for ANSI characters in message and trace introduced via #2949
