### ISSUE TITLE
Tree-view behavior, can't collapse after opened test item

### ISSUE THREAD

**Issue by gavrilfb** [allure-framework/allure2#571]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Tree-view on several pages not working correctly. Won't collapse on click after user open the test items.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Steps:
1. Open report and go to Packages menu.
2. Expand on any packages.
3. Click on any test item.
4. Click on the package name to try to collapse it.
![image](https://user-images.githubusercontent.com/29943195/29506290-27211874-8675-11e7-9275-e9c7d31fa416.png)

#### What is the expected behavior?
Package collapse the tree-view when clicked again

#### Please tell us about your environment:
| Allure version | 2.2.1 |
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Jenkins | 2.60.2 |
| Allure Jenkins Plugin | 2.22 |

**Comment by gavrilfb** [comment]
I'll just close this issue, too minor IMHO.
Also I managed to make it work by adding allure-maven to my pom.xml

**Comment by baev** [comment]
BTW the issue should be fixed in last release (2.3.4)

**Comment by maoso** [comment]
For me that is not a minor issue, in my company we use a lot the Behaviors tab with epic, features and stories and it is really annoying that the menus cannot be collapsed. 
Thank you very much

**Comment by maoso** [comment]
> I'll just close this issue, too minor IMHO.
> Also I managed to make it work by adding allure-maven to my pom.xml

About that i do not think that has any relation as i have allure-maven into my pom.xml and the issue still appears.
