### ISSUE TITLE
Allure Report: Wrong default order of TestNG DataProvider cases

### ISSUE THREAD

**Issue by ravxz** [allure-framework/allure2#734]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Wrong case order in allure-report.

Steps to reproduce:
1. Create any TestNG test class with @DataProvider and @Test methods. E.g.:
```
public class DataProviderTest {

    @DataProvider
    public Object[][] args() {
        return new String[][]{{"One"},{"Two"},{"Three"},{"Four"},{"Five"}};
    }

    @Test(dataProvider = "args")
    public void test(String arg) {
        System.out.println(arg);
    }
}
```
2. Run tests with Allure 2 enabled.
3. Generate Alllure 2 report.
4. Open report and look at cases default order (for parameters): Five, One, Three, Two, Four.

#### What is the expected behavior?

Cases order should correspond to run order: One, Two, Three, Four, Five.

#### What is the motivation / use case for changing the behavior?

Our Allure report should show cases in the order as they run.

#### Please tell us about your environment:

| Allure version | 2.x |
| --- | --- |
| Test framework | testng@6.10 |
| Allure adaptor | allure-testng@2.0-BETA21 |
| Generate report using | allure-maven@2.9 |
| Report version | 2.0.1 |

**Comment by baev** [comment]
@ravxz what version of Allure Report btw? Make sure you have latest version installed

**Comment by ravxz** [comment]
@baev, report version 2.0.1

**Comment by baev** [comment]
the issue should be fixed in latest version

**Comment by ravxz** [comment]
@baev, in 2.5.0 the issue still is present: the cases order is inverted (from the latest to the first).

**Comment by baev** [comment]
could you please attach a screenshot?

**Comment by ravxz** [comment]
Report from other project
<img width="551" alt="allure report - wrong default order" src="https://user-images.githubusercontent.com/31066181/35521093-f0daaf76-0529-11e8-93c0-e92de021101a.png">

**Comment by gavrilfb** [comment]
The order number is not in order because you use ordering by name. Use ordering by number by clicking "order".
![image](https://user-images.githubusercontent.com/29943195/35789244-7a049134-0a6d-11e8-9c80-41c4b973acc0.png)

**Comment by FluffyWeirdO** [comment]
Is there a way to set the default order by attribute? Say I would like to always have them order by the **Order** field

**Comment by ravxz** [comment]
@baev, was the default order of tests in Allure report resolved to be on execution order? Or is there report generation option for setting default order of tests?

**Comment by baev** [comment]
Please do not comment on closed issues. Create a new issue/discussion instead.
